# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homepagebanner_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='confirmed_2',
            field=models.BooleanField(default=False),
        ),
    ]
