# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_homepagebanner_confirmed_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebanner',
            name='confirmed_2',
        ),
    ]
