# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170612_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to=b'images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to=b'images'),
        ),
        migrations.AddField(
            model_name='participant',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to=b'images'),
        ),
    ]
