# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170623_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wide_image',
            field=models.ImageField(max_length=300, null=True, upload_to=b'images'),
        ),
    ]
